name: esmorga_flutter
description: "A new Flutter project."

publish_to: 'none'

version: 1.2.0+2

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any


  cupertino_icons: ^1.0.8
  http: ^1.5.0
  flutter_bloc: ^9.1.1
  get_it: ^8.2.0
  equatable: ^2.0.7
  lottie: ^3.1.3
  shared_preferences: ^2.3.4
  go_router: ^14.6.2
  hive_ce: ^2.6.0
  hive_ce_flutter: ^2.1.0
  url_launcher: ^6.3.2
  flutter_svg: ^2.0.10
  logger: ^2.0.2+1
  app_links: ^6.4.1


dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.13
  hive_ce_generator: ^1.6.0
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  mocktail: ^1.0.4


flutter:
  generate: true


  uses-material-design: true

  assets:
    - assets/animations/
    - assets/icons/
    - assets/images/

